### ISSUE TITLE
a_u=None edge case

### ISSUE THREAD

**Issue by wegank** [nix-community/label-approved#20]
I hit an edge case when relabelling NixOS/nixpkgs#301947, where the first approver (@a-n-n-a-l-e-e) deleted their account.

```
INFO:root:Processing 301947
INFO:root:lastappdate: 2024-04-06 11:06:06
INFO:root:lastcommitdate: 2024-04-05 23:44:16
INFO:root:Removing label '12.approvals: 2' from PR: '301947' https://github.com/NixOS/nixpkgs/pull/301947
INFO:root:Adding label '12.approvals: 1' to PR: '301947' https://github.com/NixOS/nixpkgs/pull/301947
Traceback (most recent call last):
  File "/nix/store/62r1p3rnaa0qw0fms8pw3i0q07if6xyp-label-approved-0.1.0/bin/.label-approved-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/62r1p3rnaa0qw0fms8pw3i0q07if6xyp-label-approved-0.1.0/lib/python3.10/site-packages/label_approved/cli.py", line 191, in main
    process_pr(g_h, p_r_as_issue.as_pull_request(), dry_run=args.dry_run)
  File "/nix/store/62r1p3rnaa0qw0fms8pw3i0q07if6xyp-label-approved-0.1.0/lib/python3.10/site-packages/label_approved/cli.py", line 148, in process_pr
    if a_u.login.lower() in maintainers:
AttributeError: 'NoneType' object has no attribute 'login'
```

**Comment by Artturin** [comment]
https://github.com/nix-community/label-approved/pull/21
